name: PR Title Checker

on:
  pull_request:
    types:
      - opened
      - edited
      - synchronize
      - labeled
      - unlabeled

jobs:
  pr_title_check:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      
      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 14
      
      - name: Run PR title check
        run: |
          node -e '
          const regex = "d2m|D2M|M2D|master to dev|dev2master|Dev to master|dev to master|[A-Za-z]+/ \[[^\]]*\](\s([A-Za-z]+\s)+)\([^)]*\)";
          const prTitle = require(process.env.GITHUB_EVENT_PATH).pull_request.title;
          
          if (!new RegExp(regex).test(prTitle)) {
            console.log(prTitle)
            console.error("PR title does not match the required pattern");
            process.exit(1);
          }
          '